services:
  web:
    build: ./
    volumes:
      - ./:/app
    ports: 
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
volumes:
  postgres_data: