services:
  backend:
    container_name: 54-dokon
    image: 54-dokon-image
    build: ./
    volumes:
      - ./:/app
    ports: 
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
      - postgres_db
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:7-alpine

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    env_file:
      - .env

  nginx:
    image: nginx:latest 
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app_network

  postgres_db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
