services:
  backend:
    container_name: 54-dokon
    image: 54-dokon-image
    command: ./start.sh
    build: ./
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    networks:
      - app_network

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:latest 
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app_network

  postgres: 
    image: postgres:latest 
    container_name: postgres 
    env_file:
      - .env
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data 
    networks: 
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
