# Generated by Django 4.2 on 2024-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'mahsulot rasmi', 'verbose_name_plural': 'mahsulot rasmlari'},
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
