# Generated by Django 4.2 on 2024-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='with_rebate',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
