# Generated by Django 4.2 on 2024-10-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productimage_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
    ]
