# Generated by Django 4.2 on 2024-10-10 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'foydalanuvchi', 'verbose_name_plural': 'foydalanuvchilar'},
        ),
        migrations.CreateModel(
            name='UsersPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.PositiveBigIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'foydalanuvchi parollari',
            },
        ),
    ]
