# Generated by Django 4.2 on 2024-10-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'kutishda'), ('shipped', "jo'natilgan"), ('delivered', 'yetkazib berildi'), ('cancelled', 'bekor qilingan')], max_length=20)),
                ('total_price', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='product.product')),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': 'buyurtmalar',
            },
        ),
    ]
